1. Getting familiar with numpy.

NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Installing numpy:
Run the following command

In [3]:
import numpy as np

Numpy arrays:
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

Creating 1D arrays:
Run the following command.

In [4]:
data= np.array([21,12],dtype='int64')
data

array([21, 12])

Creating multidimensional arrays:
Run the following command.

Method 1: List

In [6]:
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Method 2: rashape

In [9]:
data2=np.arange(1,11).reshape((2,5))
data2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Properties of array:
1. Type
2. Shape
3. Dimensions
4. Size

In [10]:

#1
print(data.dtype)

#2
print(data.shape)

#3
print(data.ndim)

#4
print(data.size)

int64
(3, 3)
2
9


2. Data manipulation.

Arithmetic operations on different arrays:

In [11]:
#1D arrays
arr1=np.array([2,4,6,8])
arr2=np.array([1,3,5,7])
print(arr1+arr2)

[ 3  7 11 15]


In [12]:
#multidimensional
arr1=np.array([[21,7,18,4],[98,6,67,8]])
arr2=np.array([[10,11,12,13],[14,15,16,17]])
print(arr1+arr2)

[[ 31  18  30  17]
 [112  21  83  25]]


Array indexing and slicing.

In [15]:
#Indexing

print(arr1[0])

# negative indexing
print(arr2[-1])

[21  7 18  4]
[14 15 16 17]


In [17]:
#slicing
print(arr1[0:])
print(arr1[-1:0])

[[21  7 18  4]
 [98  6 67  8]]
[]


3. Data aggregation techniques are:

Np.min

Np.max

Np.sum

Np.mean

Np.median

In [19]:
print(np.min(arr1))

print(np.max(arr2))

print(np.sum(arr2))

print(np.mean(arr1))

print(np.median(arr1))

4
17
108
28.625
13.0


Applications of Numpy in Data Science:

NumPy is commonly used within data science in order to work through numerical analyses and functions, such as creating and working with arrays, returning descriptive statistics, and a variety of machine learning models and mathematical formulas. You can also access the NumPy library through the GitHub platform.

Applications in Real World:

NumPy is used for numerical computing in Python. It provides support for multi-dimensional arrays, along with a vast collection of mathematical functions for array manipulation and computation.